# data
dataset: CIFAR10
data_path: /path/to/datasets

# model
type: EI-SNN
arch: VGG
num_layers: 8
T: 4
ei_ratio: 4
light_classifier: True

dropout: 0.
neuron:
  tau: 2.0

# training
epochs: 300
warmup_epochs: 10
batch_size: 128
learning_rate: 0.002
optimizer: SGD
momentum: 0.9
weight_decay: 0.0005
scheduler: CosALR
loss: CE

# logging
output_dir: /path/to/output