Parameters:
  model_type: "EISNN"
  T: 10
  arch: "VGG"
  light_classifier: True
  num_layers: 8
  ei_ratio: 4

  dataset: "CIFAR10DVS"
  data_path: "/home/data10T/data/public/cifar10dvs/cifar10_dvs"
  log_dir: "/home/data10T/lpy/LatinSNN/logs/EISNN"

  epochs: 300
  warmup_epochs: 10
  batch_size: 32
  learning_rate: 0.001
  optimizer: "SGD"
  momentum: 0.9
  weight_decay: 0.0005
  scheduler: "CosALR"
  loss: "CE"

  dropout: 0.
  neuron_config:
    tau: 2.0