# data
dataset: TinyImageNet200
data_path:  /home/data10T/data/public/tiny-imagenet-200

# model
type: EI-SNN
arch: ResNet
num_layers: 18
T: 4
ei_ratio: 4

zero_init_residual: False
neuron:
  tau: 2.0

# training
epochs: 300
warmup_epochs: 10
batch_size: 128
init_learning_rate: 0.001
learning_rate: 0.003
optimizer: SGD
momentum: 0.9
weight_decay: 0.0005
scheduler: CosALR
loss: CE

# logging
output_dir: /home/data4T1/lpy/DeepEISNN/logs/EI-SNN