# data
dataset: CIFAR10
data_path: /home/data4T1/lpy/datasets/cifar10

# model
type: BN-SNN
arch: VGG
num_layers: 8
T: 4
light_classifier: True

dropout: 0.
neuron: # configuration of spiking LIF neurons
  tau: 2.0

# training
epochs: 300
batch_size: 128
learning_rate: 0.1
optimizer: SGD
momentum: 0.9
weight_decay: 0.0001
scheduler: CosALR
loss: CE

# logging
output_dir: /home/data4T1/lpy/DeepEISNN/logs/BN-SNN