model_type: "SNN"
T: 4
arch: "VGG"
num_layers: 11
light_classifier: True

BN: True
dropout: 0.
neuron_config:
  tau: 2.0

dataset: "CIFAR100"
data_path: "/home/data4T1/lpy/datasets/cifar100"
log_dir: "/home/data4T1/lpy/DeepEISNN/logs/BN-SNN"

epochs: 300
batch_size: 128
learning_rate: 0.1
optimizer: "SGD"
momentum: 0.9
weight_decay: 0.0001
scheduler: "CosALR"
T_max: 300
loss: "CE"